CREATE WAREHOUSE SPARKIFY_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;


CREATE DATABASE SPARKIFY_DB;
CREATE SCHEMA SPARKIFY_DB.RAW;
CREATE SCHEMA SPARKIFY_DB.STAGING;
CREATE SCHEMA SPARKIFY_DB.MARTS;






