CREATE OR REPLACE STORAGE INTEGRATION SPARKIFY_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'bucket-aws-role-arn'
  STORAGE_ALLOWED_LOCATIONS = ('bucket-url');

DESCRIBE INTEGRATION SPARKIFY_S3_INTEGRATION;

CREATE OR REPLACE STAGE SPARKIFY_S3_STAGE
    URL = 'bucket-url'
    STORAGE_INTEGRATION = SPARKIFY_S3_INTEGRATION;

    LIST @SPARKIFY_DB.RAW.SPARKIFY_S3_STAGE;


CREATE OR REPLACE FILE FORMAT SPARKIFY_DB.RAW.JSON_FORMAT
    TYPE = JSON;

SELECT *
FROM @SPARKIFY_DB.RAW.SPARKIFY_S3_STAGE/song_data/
(FILE_FORMAT => SPARKIFY_DB.RAW.JSON_FORMAT);


SELECT *
FROM @SPARKIFY_DB.RAW.SPARKIFY_S3_STAGE/log_data/
(FILE_FORMAT => SPARKIFY_DB.RAW.JSON_FORMAT);   


