COPY INTO SPARKIFY_DB.RAW.SONG_DATA_RAW
FROM @SPARKIFY_DB.RAW.SPARKIFY_S3_STAGE/song_data/
FILE_FORMAT = (FORMAT_NAME = SPARKIFY_DB.RAW.JSON_FORMAT);

COPY INTO SPARKIFY_DB.RAW.LOG_DATA_RAW
FROM @SPARKIFY_DB.RAW.SPARKIFY_S3_STAGE/log_data/
FILE_FORMAT = (FORMAT_NAME = SPARKIFY_DB.RAW.JSON_FORMAT);